export const galleryItems = [
  {
    preview: "./img/1.jpg",
    original: "./pages.html",
    alt: "Перший місяць",
    description: "Ось так я провела свій перший місяць",
    cat: 0,
  },
  {
    preview: "./img/2.jpg",
    original: "./pages.html",
    alt: "Другий місяць",
    description: "Другий місяць - а я вже стільки заробляю!",
    cat: 1,
  },
  {
    preview: "./img/3.jpg",
    original: "./pages.html",
    alt: "Третій місяць",
    description: "Раз-два і трієчка",
    cat: 2,
  },
  {
    preview: "./img/4.jpg",
    original: "./pages.html",
    alt: "Четвертий місяць",
    description: "2 + 2 = 4!",
    cat: 3,
  },
  {
    preview: "./img/5.jpg",
    original: "./pages.html",
    alt: "П'ятий місяць",
    description: "Пятьорік",
    cat: 4,
  },
  {
    preview: "./img/6.jpg",
    original: "./pages.html",
    alt: "Шостий місяць",
    description: "Ось і перше тістечко на півроку",
    cat: 5,
  },
  {
    preview: "./img/7.jpg",
    original: "./pages.html",
    alt: "Сьомий місяць",
    description: "Після півроку - Сімка, а ви що думали?",
    cat: 6,
  },
  {
    preview: "./img/8.jpg",
    original: "./pages.html",
    alt: "Восьмий місяць",
    description: "Змучили мене на вісім, відпочивала",
    cat: 7,
  },
  {
    preview: "./img/9.jpg",
    original: "./pages.html",
    alt: "Дев'ятий місяць",
    description: "Фруктова дев'ятка!",
    cat: 8,
  },
  {
    preview: "./img/10.jpg",
    original: "./pages.html",
    alt: "Десятий місяць",
    description: "Десятка - пора би і напитись!",
    cat: 9,
  },
  {
    preview: "./img/11.jpg",
    original: "./pages.html",
    alt: "Одиннадцятий місяць",
    description: "Одинадцять - треба і заїсти солодкого",
    cat: 10,
  },
  {
    preview: "./img/12.webp",
    original: "./pages.html",
    alt: "Дванадцятий місяць",
    description: "Тут буде моє фото, СКОРО!!!",
    cat: 11,
  },
];
